### ISSUE TITLE
Does it support vim-plug? I can't get it to work

### ISSUE THREAD

**Issue by Gaulm** [davisdude/vim-love-docs#22]
Hello, I'm having difficulties with this plugin, the installation is fine, the plugin is installed, but nothing works:
the syntax is not highlighted and `:help love.txt` produces an error.
Any idea? Honestly I don't think it's related to vim-plug, maybe is it because I'm using neovim instead of vim?

**Comment by davisdude** [comment]
I've never used neovim or vim-plug, so it's very possible those could be the issues. However, after looking at vim-plug some, I have a feeling that vim-love-docs is not being "installed" correctly. By default, I have all of the content responsible for highlighting, help docs, etc. `.gitignore`d because they cause messy and cluttered diffs.

However, I have another branch which does include all the outputs which you should be able to use. Based on the documentation, try this (untested):

```vim
Plug 'davisdude/vim-love-docs', { 'branch': 'build' }
```

I sometimes forget to update that branch, so if you want to be sure you're running the latest and greatest, you could try this instead (also untested):

```vim
Plug 'davisdude/vim-love-docs', { 'do': './src/gen.sh' }
```

Please let me know if this takes care of it.

**Comment by Gaulm** [comment]
Solved using `Plug 'davisdude/vim-love-docs', { 'branch': 'build' }`
Thank you
